# Generated by Django 4.1.1 on 2022-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
